# Config for https://github.com/apps/probot-cc

vars:
  - name: $BRANCH_SUFFIX
    value: TEST_SUFFIX

pull_request:
  opened:
    template: |
      Here's a helpful URL based on the branch name: https://$BRANCH-$BRANCH_SUFFIX.something.example.com
      Second line goes here. 
      BRANCH is: $BRANCH
      BRANCH_SUFFIX is: $BRANCH_SUFFIX
      BRANCH_SANITIZED is: $BRANCH_SANITIZED
      Done.
